CREATE DATABASE LAB_3_FITCLUB;

USE LAB_3_FITCLUB;

CREATE TABLE SOCIOS 
(
	CEDULA CHAR(13) 
		CONSTRAINT PK_SOCIOS PRIMARY KEY
		CONSTRAINT CK_SOCIOS_CEDULA CHECK
			(
				CEDULA like '[0][1-9][-][0-9][0-9][0-9][0-9][-][0-9][0-9][0-9][0-9][0-9]'
			or  
				CEDULA like '[1][0-3][-][0-9][0-9][0-9][0-9][-][0-9][0-9][0-9][0-9][0-9]'
			),
	NUM_SOCIO INT IDENTITY NOT NULL
		CONSTRAINT UK_PHONE_SOCIO UNIQUE,
	NOMBRE_DOMICILIO VARCHAR(200)
);

CREATE TABLE INSTRUCTOR 
(
	CEDULA CHAR(13)
		CONSTRAINT PK_INSTRUCTOR PRIMARY KEY
		CONSTRAINT CK_INSTRUCTOR_CEDULA CHECK
			(
				CEDULA like '[0][1-9][-][0-9][0-9][0-9][0-9][-][0-9][0-9][0-9][0-9][0-9]'
			or  
				CEDULA like '[1][0-3][-][0-9][0-9][0-9][0-9][-][0-9][0-9][0-9][0-9][0-9]'
			),
	NOMBRE VARCHAR(30),
	DOMICILIO VARCHAR(200)
);

CREATE TABLE CATEGORIA
(
	COD_CATEGORIA INT 
		CONSTRAINT PK_CATEGORIA PRIMARY KEY,
	NOMBRE VARCHAR(15)
		CONSTRAINT CK_NOMBRE_CATEGORIA CHECK
		(
			NOMBRE IN ('maquina', 'baile', 'speeding', 'pesas')
		),
	DIA_SEMANA VARCHAR(15)
		CONSTRAINT CK_DIA_SEMANA CHECK
		(
			DIA_SEMANA IN ('lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado')
		)
			DEFAULT 'sábado',
	CEDULA CHAR(13)
		CONSTRAINT FK_CATEGORIA_CEDULA FOREIGN KEY
		REFERENCES INSTRUCTOR(CEDULA) ON DELETE SET NULL
		DEFAULT NULL
);

CREATE TABLE INSCRIPCION
(
	CEDULA_SOCIO CHAR(13)
		CONSTRAINT FK_INSCRIPCION_CEDULA FOREIGN KEY
		REFERENCES SOCIOS(CEDULA) ON DELETE CASCADE,
	COD_CATEGORIA INT
	CONSTRAINT FK_INSCRIPCION_CATEGORIA FOREIGN KEY
		REFERENCES CATEGORIA(COD_CATEGORIA) ON DELETE CASCADE,
	MATRICULA CHAR(1) DEFAULT 'n'
		CONSTRAINT CK_MATRICULA_INSCRIPCION CHECK
		(
			MATRICULA IN ('s','n')
		),
	MONTO_PAGAR FLOAT
		CONSTRAINT CK_MONTO_PAGAR CHECK
		(
			MONTO_PAGAR > 0
		)
	CONSTRAINT PK_INSCRIPCION PRIMARY KEY(CEDULA_SOCIO, COD_CATEGORIA)
);

